services:
  guaripe-backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: localhost:5000/guaripe/backend:latest
    ports:
      - '4201:3000'
    volumes:
      - ./apps/backend:/app
    container_name: guaripe-backend
    environment:
    environment:
      # 'host.docker.internal' permite acessar o banco que está rodando no Host
      - DATABASE_URL=postgresql://user:password@host.docker.internal:5432/guaripe_dev
      - PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Para desenvolvimento local, usamos um banco local ou conectamos via tunnel/vpn
    # Não tentamos conectar na rede de produção diretamente aqui para evitar acidentes.

  guaripe-frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: localhost:5000/guaripe/frontend:latest
    ports:
      - '4202:80'
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    container_name: guaripe-frontend
    environment:
      - VITE_API_URL=http://localhost:4201
